title: Mallorca Developers User Group
description: The landing page for Mallorca Developers User Group
url: "http://mallorcadevelopers.github.io"
image: "http://sevilladevelopers.github.io/assets/img/sevilla-developers-icon.png"

#SEO
twitter:
  username: MallorcaDevelopers
facebook:
 publisher: mallocadevelopers

# Google Analytics Code
codega: UA-96791038-1

gems:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ['README.md', 'CNAME', 'Gemfile', 'Gemfile.lock', 'package.json', 'assets/css/vendor']

# Sass settings
sass:
  sass_dir: assets/css
  style: :compressed
